canonical: https://gematik.de/fhir/dipag
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.5.4
  de.gematik.ti: 1.1.1
  hl7.fhir.extensions.r5: 4.0.1